#!/usr/bin/env bash

set -x;

if [ -z "$VERSION" ]; then
    VERSION=$(node -e "console.log(require('./package.json').version)")
fi

if [ -z "$NAME" ]; then
    NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")
fi

PREFIX=$(node -e "console.log(require('./package.json')['docker-registry'] || '')")
if [ -z "$PREFIX" ]; then
    PREFIX=$(node -e "console.log(require('./package.json')['docker-user'] || '')")
fi

if [ -z "$PREFIX" ]; then
    echo "docker push requires either docker-registry or docker-user in package.json"
    exit 1
fi

echo "$VERSION"

docker push "$PREFIX/$NAME:$VERSION"
docker push "$PREFIX/$NAME:latest"